# taken from https://gitlab.com/PPW-2017/ppw-lab-ki/blob/master/.gitlab-ci.yml and https://gitlab.com/ilmannafian04/ppw-lab-template/-/blob/master/.gitlab-ci.yml
stages:
  - test
  - deploy

Deployment:
  stage: deploy
  image: ruby
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY